#!/bin/bash -e
# pi-gen substage: install BlinkPi into the image.
#
# Runs on the build host with ${ROOTFS_DIR} pointing at the image's root;
# `on_chroot` runs commands inside the image (via qemu-user-static).

FILES="$(dirname "$0")/files"
USER_HOME="/home/${FIRST_USER_NAME}"
PROJECT="${USER_HOME}/BlinkPi"

# ── project files ─────────────────────────────────────────────────────
install -d "${ROOTFS_DIR}${PROJECT}"
rsync -a "${FILES}/BlinkPi/" "${ROOTFS_DIR}${PROJECT}/"
on_chroot <<EOF
chown -R ${FIRST_USER_NAME}:${FIRST_USER_NAME} "${PROJECT}"
EOF

# ── Python venv with the package (+ web extras for the UI and setup page) ──
on_chroot <<EOF
set -e
cd "${PROJECT}"
sudo -u ${FIRST_USER_NAME} python3 -m venv .venv
sudo -u ${FIRST_USER_NAME} .venv/bin/pip install --upgrade pip wheel
sudo -u ${FIRST_USER_NAME} .venv/bin/pip install -e ".[web]"
EOF

# ── USB gadget (dwc2) so the first Apply needs no reboot ─────────────
CONFIGTXT="${ROOTFS_DIR}/boot/firmware/config.txt"
CMDLINE="${ROOTFS_DIR}/boot/firmware/cmdline.txt"
[[ -f "$CONFIGTXT" ]] || CONFIGTXT="${ROOTFS_DIR}/boot/config.txt"
[[ -f "$CMDLINE" ]] || CMDLINE="${ROOTFS_DIR}/boot/cmdline.txt"
if ! grep -q "dtoverlay=dwc2,dr_mode=peripheral" "$CONFIGTXT"; then
    cat >> "$CONFIGTXT" <<'EOF'

# blink-usb-bridge: Pi-as-USB-gadget mode for SM2
[all]
dtoverlay=dwc2,dr_mode=peripheral
EOF
fi
if ! grep -q "modules-load=dwc2" "$CMDLINE"; then
    sed -i 's/$/ modules-load=dwc2/' "$CMDLINE"
fi

# ── captive portal DNS while the setup hotspot is up ─────────────────
# NetworkManager runs dnsmasq for "shared" connections and reads extra
# config from this directory; answering every name with the hotspot IP
# makes phones/laptops pop their "sign in to network" page.
install -d "${ROOTFS_DIR}/etc/NetworkManager/dnsmasq-shared.d"
install -m 0644 "${FILES}/blinkpi-captive.conf" "${ROOTFS_DIR}/etc/NetworkManager/dnsmasq-shared.d/blinkpi-captive.conf"

# ── setup page service (everything else is generated by install.sh at Apply) ──
sed "s|@PROJECT_DIR@|${PROJECT}|g" "${ROOTFS_DIR}${PROJECT}/systemd/blink-setup.service.template" \
    > "${ROOTFS_DIR}/etc/systemd/system/blink-setup.service"
on_chroot <<EOF
systemctl enable blink-setup.service
systemctl enable avahi-daemon.service
systemctl enable NetworkManager.service
systemctl enable ssh.service
EOF

# ── console banner ───────────────────────────────────────────────────
install -m 0644 "${FILES}/motd" "${ROOTFS_DIR}/etc/motd"
